package game.model.forest;

/**
 * Troll Cave dialogue: Prince, Darabongba, Troll Boss.
 * Each line: [speaker, text, princeExpr, darabongbaExpr, trollExpr].
 * All text in English for future language system.
 */
public final class TrollCaveData {
    private TrollCaveData() {}

    public static final String TROLL_DEFAULT = "default";
    public static final String TROLL_ANGRY = "angry";

    /** Lines: speaker, text, princeExpr, darabongbaExpr, trollExpr */
    public static final String[][] LINES = {
        {"Prince", "Why does this cave feel… opinionated?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Because it is.\nAnd it already decided you're wrong.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "I didn't even say anything yet.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Exactly. Rookie mistake.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "That makes no sense.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Welcome to modern discourse.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "The walls are literally staring at me.", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Those are not walls. Those are comment sections.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "That's worse.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Prince", "Why is everything purple?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Because this place runs on low-resolution rage.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Did the ground just shake?", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Either an earthquake…\nor someone posted a bad take.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "What kind of take causes earthquakes?", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "\"Cereal is soup.\"", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "No.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Yes.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We should leave.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "We can't.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Why?", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Because the game designer hates you.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "That's fair.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Prince", "What is that thing in the center?", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "That…\nis where opinions go to become consequences.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "It looks like a portal.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "It is.\nA portal to accountability.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "I don't like that word.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Nobody here does.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "It's getting bigger.", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Yeah.\nSomething's coming.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_NERVOUS, TROLL_DEFAULT},
        {"Prince", "We should hide.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "From what?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "I don't know.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Exactly.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "Well… well… well…", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "Nope.", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Yep.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Who are you?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "I am the consequence of your actions.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "He means he's unemployed.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "Silence.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "Make me.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Please don't provoke the giant floating face.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "It provoked me first by existing.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "I have watched everything.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "That's creepy.", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "Every post.\nEvery comment.\nEvery terrible opinion.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "So… you're like the internet, but louder.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "Prince.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "Yes?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "You laughed at a joke without fact-checking it.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "I thought it was funny.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "That is not a defense.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "It should be.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "And you…", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "Don't say it.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_NERVOUS, TROLL_DEFAULT},
        {"Troll Boss", "You typed \"first\" under a video.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "I was young.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "You did what?", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "We all have a past.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "Your past has been archived.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "Archived?", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Oh no.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_NERVOUS, TROLL_DEFAULT},
        {"Prince", "What does that mean?", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "It means he has receipts.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "I have screenshots.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "We're doomed.", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Can we apologize?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_NERVOUS, TROLL_DEFAULT},
        {"Prince", "Yes, let's apologize.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "Too late.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "We didn't even try yet.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "I reject your future apology.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "That's efficient.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "What do you want from us?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "Justice.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "Define justice.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "You will face trial.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "Trial for what?", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "Everything.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "That's not specific.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "It doesn't need to be.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "He's got us there.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Can we just leave?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "No.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "Can we run?", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "No.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "Can we alt+F4?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "No.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "What can we do?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "You can try to survive.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "That sounds like a boss fight.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Wait, wait, wait.\nWe can talk this out.", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "You already did.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "No, I mean calmly.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "This is calm.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "I hate to see you angry then.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "The internet has spoken.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "The internet is not a person.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Have you met the internet?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "This is ridiculous.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "And yet, here you are.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "He's winning the argument.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Stop helping him.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Prince", "What happens if we lose?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "You get cancelled.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "What does that actually mean?", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Nobody knows.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "It means…\nyou disappear.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "I don't like that.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "I strongly dislike that.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "What happens if we win?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "You get to leave.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "That's it?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "And your reputation survives.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "That sounds important.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "More important than your health, apparently.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "This is insane.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "This is standard.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "We are absolutely not prepared for this.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_NERVOUS, TROLL_DEFAULT},
        {"Prince", "Speak for yourself.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "I am speaking for both of us.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Fine.\nWhat do we have to do?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "Dodge.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Prince", "Dodge what?", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Troll Boss", "Everything.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Darabongba", "He's definitely a boss.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Any final advice?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Yes.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "What?", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Don't get hit.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "That's not helpful.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "It's accurate.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Troll Boss", "Begin.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
    };

    /** Post-battle dialogue (after victory). Same format: speaker, text, princeExpr, darabongbaExpr, trollExpr. */
    public static final String[][] POST_BATTLE_LINES = {
        {"Troll Boss", "…", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"Troll Boss", "You survived.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Prince", "We did it?", ForestEntranceData.EXPR_SURPRISE, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "We're not cancelled?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_SURPRISE, TROLL_DEFAULT},
        {"Troll Boss", "For now.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_ANGRY},
        {"", "(Boss disappears.)", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "I'm never going online again.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "You say that every time.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "And I never mean it.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
    };

    /** Doge Shrine discussion (Prince/Darabongba). Same format. */
    public static final String[][] DOGE_SHRINE_LINES = {
        {"Prince", "So… we survived.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Define \"survived.\"", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We're alive.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Physically. Not emotionally.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We got the Troll Mask.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Yes. A mask from a guy who hates everyone.\nVery reassuring.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "That means we can move on.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Move on to where?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Well, we have options.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "No, we have bad options.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "There's the shrine.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Ah yes. The place where dogs judge your soul.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Or the radio tower.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "The place that weaponizes music.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "You're being dramatic.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "I am being realistic.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "The shrine sounds peaceful.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Nothing with a currency is peaceful.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "It's just Doge Coin.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Exactly. Financial instability.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Okay, what about the radio tower?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Let me guess.\nWe go there…\nand suddenly we can't leave.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "That sounds like every place we've been.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Fair.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We need another clue.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "We need therapy.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Focus.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "I am focused.\nOn how bad our situation is.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "The shrine gives us a coin.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Yes.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "The tower gives us… something.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Psychological damage.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We can't just stand here.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "We absolutely can.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "No we can't.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Watch me.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "You're not moving.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "That's the plan.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We have to pick a direction.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Fine. I pick \"away.\"", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "That's not a direction.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "It is emotionally.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Think logically.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Logic got us into a cave with a floating face.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We need progress.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Progress is overrated.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "You're impossible.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "And yet, I'm your guide.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "That was never confirmed.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "It was implied.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "By who?", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Me.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "That doesn't count.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "It does if I say it confidently.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We're going to the shrine.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "I veto that.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "You don't have veto power.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "I have strong opinions.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "That's not the same thing.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "It is on the internet.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We need the coin.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "We need safety.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We're never safe.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Exactly. So why try?", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Because that's how games work.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "I hate games.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "You are in a game.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "That explains a lot.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "We go to the shrine.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "I still disagree.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Noted.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Ignored.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Moving on.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Regret incoming.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Come on.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "If we get judged again, I'm blaming you.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "You already blame me for everything.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "And I will continue to do so.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
        {"Prince", "Let's go.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "I have a bad feeling.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_NERVOUS, TROLL_DEFAULT},
        {"Prince", "You always have a bad feeling.", ForestEntranceData.EXPR_ANNOYED, ForestEntranceData.EXPR_DEFAULT, TROLL_DEFAULT},
        {"Darabongba", "Because I'm always right.", ForestEntranceData.EXPR_DEFAULT, ForestEntranceData.EXPR_RESENTMENT, TROLL_DEFAULT},
    };
}
